from pathlib import Path


def replace_one(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"Expected source block not found in {path}: {old[:120]!r}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


def insert_after(path: str, anchor: str, addition: str) -> None:
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if anchor not in text:
        raise SystemExit(f"Anchor not found in {path}: {anchor[:120]!r}")
    p.write_text(text.replace(anchor, anchor + addition, 1), encoding="utf-8")


# 1) Atomic visual prompt: distinguish series-level counted themes from one Work Unit subject,
#    and keep batch-count prose out of renderer-facing HARD text.
path = "src/Diez.Core/DiezVisualHardPromptFrontendBridge.cs"
replace_one(path, "using System.Text;\nusing System.Text.Json;", "using System.Text;\nusing System.Text.Json;\nusing System.Text.RegularExpressions;")
replace_one(
    path,
    "internal static class VisualHardPromptContractCompiler\n{\n    public static string Build(PreviewProject project, AiExchangeWorkUnit unit)",
    '''internal static class VisualHardPromptContractCompiler\n{\n    private static readonly Regex AggregateSeriesSubjectRegex = new(\n        @\"^\\s*(?<count>\\d+|one|two|three|four|five|six|seven|eight|nine|ten|uno|una|due|tre|quattro|cinque|sei|sette|otto|nove|dieci)\\s+(?:soggett[oi]|subjects?|personagg(?:io|i)|characters?)\\b(?:\\s+(?:di|del|della|dei|delle|a\\s+tema|of|for|themed(?:\\s+around)?))?\\s*(?<theme>.*)$\",\n        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Compiled);\n\n    private static readonly Regex BatchImageCountRegex = new(\n        @\"\\b(?:\\d+|one|two|three|four|five|six|seven|eight|nine|ten|uno|una|due|tre|quattro|cinque|sei|sette|otto|nove|dieci)\\s+(?:images?|immagin[ei])\\b\",\n        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Compiled);\n\n    private static readonly Regex OneCanvasManyIllustrationsRegex = new(\n        @\"(?:un.?unica|una\\s+sola|single|one)\\s+(?:image|immagine).*?(?:\\d+|multiple|piu|più)\\s+(?:illustrazion\\w*|images?|immagin\\w*|pictures?)\",\n        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Compiled);\n\n    public static string Build(PreviewProject project, AiExchangeWorkUnit unit)''')
replace_one(
    path,
    '''        var subject = focal?.Name?.Trim();\n        if (string.IsNullOrWhiteSpace(subject)) subject = (item?.Subject ?? string.Empty).Trim();\n        if (string.IsNullOrWhiteSpace(subject)) subject = (request.Subject ?? string.Empty).Trim();\n        if (string.IsNullOrWhiteSpace(subject)) subject = \"the requested focal subject\";\n''',
    '''        var subject = focal?.Name?.Trim();\n        var hasAtomicSubject = !string.IsNullOrWhiteSpace(subject);\n        if (!hasAtomicSubject && !string.IsNullOrWhiteSpace(item?.Subject))\n        {\n            subject = item!.Subject.Trim();\n            hasAtomicSubject = true;\n        }\n\n        var seriesSubject = (request.Subject ?? string.Empty).Trim();\n        var aggregateSeriesSubject = !hasAtomicSubject && IsAggregateSeriesSubject(seriesSubject, request.SeriesCount);\n        if (!hasAtomicSubject && aggregateSeriesSubject)\n            subject = AtomicSubjectFromSeriesTheme(seriesSubject);\n        else if (!hasAtomicSubject)\n            subject = seriesSubject;\n        if (string.IsNullOrWhiteSpace(subject)) subject = \"the requested focal subject\";\n''')
replace_one(
    path,
    '''        var sb = new StringBuilder();\n        sb.AppendLine(string.Equals(request.BookType, BookTypeProfileService.ColoringBook, StringComparison.OrdinalIgnoreCase)\n            ? \"Create ONE finished, publication-quality coloring-book illustration.\"\n            : \"Create ONE finished, publication-quality editorial image.\");\n        sb.AppendLine(VisualPromptIntentSynthesizer.BuildWorkUnitDirection(project, request, subject, scene, participants));\n        sb.AppendLine($\"PRIMARY SUBJECT — HARD LOCK: {subject}. The subject must be dominant, large, immediately recognizable, anatomically coherent for the selected style and more visually important than the background.\");\n''',
    '''        var sb = new StringBuilder();\n        sb.AppendLine(string.Equals(request.BookType, BookTypeProfileService.ColoringBook, StringComparison.OrdinalIgnoreCase)\n            ? \"Create ONE finished, publication-quality coloring-book illustration.\"\n            : \"Create ONE finished, publication-quality editorial image.\");\n        if (aggregateSeriesSubject)\n        {\n            sb.AppendLine($\"SERIES SUBJECT ASSIGNMENT — HARD: the user phrase '{seriesSubject}' describes the SERIES, not the contents of this single canvas. This is item {position} of {request.SeriesCount}. Assign exactly ONE concrete, specific, immediately recognizable subject to this Work Unit before rendering. Across the batch, use a different concrete subject for each sibling Work Unit unless the user explicitly requests repetition. Never draw the numeric series count, multiple alternative subjects, a contact sheet or several sibling illustrations on this canvas.\");\n        }\n        sb.AppendLine(VisualPromptIntentSynthesizer.BuildWorkUnitDirection(project, request, subject, scene, participants));\n        sb.AppendLine($\"PRIMARY SUBJECT — HARD LOCK: {subject}. The subject must be dominant, large, immediately recognizable, structurally coherent for the selected style and more visually important than the background. If a viewer cannot name the intended subject immediately at thumbnail size, the asset FAILS and must be regenerated.\");\n''')
replace_one(
    path,
    '''        var required = Join(request.MustDo, item?.MustDo);\n        var excluded = Join(request.MustNotDo, item?.MustNotDo);\n        if (!string.IsNullOrWhiteSpace(required)) sb.AppendLine(\"USER REQUIREMENT — HARD: \" + required);\n        if (!string.IsNullOrWhiteSpace(excluded)) sb.AppendLine(\"USER EXCLUSION — HARD: \" + excluded);\n''',
    '''        var required = AtomicUserConstraint(Join(request.MustDo, item?.MustDo), exclusion: false);\n        var excluded = AtomicUserConstraint(Join(request.MustNotDo, item?.MustNotDo), exclusion: true);\n        if (!string.IsNullOrWhiteSpace(required)) sb.AppendLine(\"USER REQUIREMENT — HARD: \" + required);\n        if (!string.IsNullOrWhiteSpace(excluded)) sb.AppendLine(\"USER EXCLUSION — HARD: \" + excluded);\n''')
insert_after(
    path,
    '''        return PromptEnglishNormalizer.NormalizeProviderFacing(sb.ToString()).Trim();\n    }\n''',
    '''\n    private static bool IsAggregateSeriesSubject(string? value, int seriesCount)\n    {\n        if (seriesCount <= 1 || string.IsNullOrWhiteSpace(value)) return false;\n        return AggregateSeriesSubjectRegex.IsMatch(value.Trim());\n    }\n\n    private static string AtomicSubjectFromSeriesTheme(string value)\n    {\n        var match = AggregateSeriesSubjectRegex.Match(value ?? string.Empty);\n        var theme = match.Success ? match.Groups[\"theme\"].Value.Trim(' ', ':', '-', '–', '—') : string.Empty;\n        return string.IsNullOrWhiteSpace(theme)\n            ? \"one concrete, specific, immediately recognizable subject fitting the user's series theme\"\n            : $\"one concrete, specific, immediately recognizable subject fitting the theme: {theme}\";\n    }\n\n    private static string AtomicUserConstraint(string? value, bool exclusion)\n    {\n        var kept = new List<string>();\n        foreach (var line in Lines(value ?? string.Empty))\n        {\n            if (BatchImageCountRegex.IsMatch(line)) continue;\n            if (exclusion && OneCanvasManyIllustrationsRegex.IsMatch(line))\n            {\n                kept.Add(\"Do not combine multiple requested series illustrations into one canvas.\");\n                continue;\n            }\n            kept.Add(line);\n        }\n        return string.Join(Environment.NewLine, kept.Distinct(StringComparer.OrdinalIgnoreCase));\n    }\n''')

# 2) Batch prompt: explicitly resolve a counted theme once across the whole batch.
path = "src/Diez.Core/DiezPromptPackBatchFrontendBridge.cs"
replace_one(
    path,
    '''        sb.AppendLine(\"1. Tratta ogni blocco DIEZ VISUAL PROMPT come una richiesta di rendering indipendente, ma gestisci l'intero lotto all'interno di questa consegna ZIP.\");\n        sb.AppendLine(\"2. Genera una sola immagine finale per blocco. Non creare collage, griglie, contact sheet, tavole multiple o alternative nello stesso asset.\");\n        sb.AppendLine(\"3. Mantieni fra immagini soltanto le regole Consistent espresse nei prompt. Non trascinare automaticamente soggetti, pose, oggetti o Scene specifiche dal blocco precedente.\");\n        sb.AppendLine(\"4. `prompt-manifest.json` contiene gli identificatori tecnici necessari a Diez per ricomporre i risultati. Usali soltanto nel Response Pack e non inserirli nelle immagini né nei prompt del renderer.\");\n        sb.AppendLine(\"5. Eventuali reference/materiali sono sotto `inputs/` e vanno usati solo per i ruoli dichiarati nel manifest. Non inferire un uso diverso dal ruolo editoriale indicato dal publisher.\");\n        sb.AppendLine(\"6. Ogni risultato rientra come Candidate. Non approvare implicitamente: Vision/review e `Porta nel libro` restano fasi Diez separate.\");\n        sb.AppendLine(string.IsNullOrWhiteSpace(expectedResponse)\n            ? \"7. Al termine restituisci, quando il sistema lo consente, UN SOLO Response ZIP `diez-response` contenente un risultato distinto per ogni Work Unit del manifest.\"\n            : $\"7. Al termine restituisci, quando il sistema lo consente, UN SOLO Response ZIP chiamato ESATTAMENTE `{expectedResponse}`, contenente un risultato distinto per ogni Work Unit del manifest.\");\n''',
    '''        sb.AppendLine(\"1. Tratta ogni blocco DIEZ VISUAL PROMPT come una richiesta di rendering indipendente, ma gestisci l'intero lotto all'interno di questa consegna ZIP.\");\n        sb.AppendLine(\"2. Genera una sola immagine finale per blocco. Non creare collage, griglie, contact sheet, tavole multiple o alternative nello stesso asset.\");\n        sb.AppendLine(\"3. Se il publisher ha espresso il soggetto come conteggio/tema di serie (es. '3 soggetti di Halloween') invece che come nomi atomici, crea PRIMA un piano soggetti per l'intero lotto: assegna un soggetto concreto, riconoscibile e distinto a ciascuna Work Unit e mantieni quell'assegnazione durante tutti i rendering. Il numero della serie non è contenuto visivo della singola immagine.\");\n        sb.AppendLine(\"4. Mantieni fra immagini soltanto le regole Consistent espresse nei prompt. Non trascinare automaticamente pose, oggetti o Scene specifiche dal blocco precedente; un soggetto assegnato resta invece quello della propria Work Unit.\");\n        sb.AppendLine(\"5. Prima di accettare un risultato, scartalo e rigeneralo se appare come bozza, scarabocchio, primitive geometriche, placeholder, icon sheet, diagramma o pagina non commercialmente pubblicabile, anche se il tema generale è intuibile.\");\n        sb.AppendLine(\"6. `prompt-manifest.json` contiene gli identificatori tecnici necessari a Diez per ricomporre i risultati. Usali soltanto nel Response Pack e non inserirli nelle immagini né nei prompt del renderer.\");\n        sb.AppendLine(\"7. Eventuali reference/materiali sono sotto `inputs/` e vanno usati solo per i ruoli dichiarati nel manifest. Non inferire un uso diverso dal ruolo editoriale indicato dal publisher.\");\n        sb.AppendLine(\"8. Ogni risultato rientra come Candidate. Non approvare implicitamente: Vision/review e `Porta nel libro` restano fasi Diez separate.\");\n        sb.AppendLine(string.IsNullOrWhiteSpace(expectedResponse)\n            ? \"9. Al termine restituisci, quando il sistema lo consente, UN SOLO Response ZIP `diez-response` contenente un risultato distinto per ogni Work Unit del manifest.\"\n            : $\"9. Al termine restituisci, quando il sistema lo consente, UN SOLO Response ZIP chiamato ESATTAMENTE `{expectedResponse}`, contenente un risultato distinto per ogni Work Unit del manifest.\");\n''')

# 3) Vision: explicit commercial/editorial readiness HARD gate.
path = "src/Diez.Core/VisionHardGatePolicy.cs"
replace_one(path, '    public const string DrawingCraft = "drawing_craft";\n', '    public const string DrawingCraft = "drawing_craft";\n    public const string EditorialReadiness = "editorial_readiness";\n')
replace_one(path, '        DrawingCraft,\n        ColorableRegions,', '        DrawingCraft,\n        EditorialReadiness,\n        ColorableRegions,')
replace_one(
    path,
    '- `drawing_craft` — HARD for Coloring: coherent anatomy/structure, intentional organic contours and usable geometry. Obvious malformed anatomy, primitive placeholder construction, accidental duplicates or meaningless filler fail.\n',
    '- `drawing_craft` — HARD for Coloring: coherent anatomy/structure, intentional organic contours and usable geometry. Obvious malformed anatomy, primitive placeholder construction, accidental duplicates or meaningless filler fail.\n- `editorial_readiness` — HARD: judge the candidate as a paid publishing asset, not as an AI demo. A scribble, rough sketch, primitive clip-art, placeholder, exercise sheet or merely interpretable draft is FAIL even when the theme can be guessed.\n')

path = "src/Diez.Core/DiezVisionFrontendBridge.cs"
insert_after(
    path,
    '''            result.Add(new(VisionHardGatePolicy.DrawingCraft,\n                \"Qualità del disegno\",\n                \"Anatomia/struttura coerente nello stile scelto, contorni intenzionali e organici, silhouette leggibile; niente primitive geometriche rozze, arti/forme malformati, duplicazioni o filler senza senso.\", true));\n''',
    '''            result.Add(new(VisionHardGatePolicy.EditorialReadiness,\n                \"Qualità editoriale / pubblicabile\",\n                \"La pagina deve sembrare un'illustrazione finita che un editore potrebbe inserire in un libro da colorare a pagamento: niente scarabocchi, bozza, primitive, clip-art grezza, placeholder, esercizio tecnico o resa solo vagamente interpretabile.\", true));\n''')

# 4) Vision UI: provider description is descriptive metadata, never proof.
path = "src/Diez.Uno/VisionWorkspace.cs"
replace_one(
    path,
    '            Text = "Importa l\'immagine candidata con la sua descrizione, poi verifica tutti i controlli richiesti da Diez. Vision approva la versione; l\'applicazione al libro resta una seconda azione esplicita. Il divisore fra controlli e anteprima può essere trascinato.",',
    '            Text = "Importa l\'immagine candidata e guarda i pixel reali. La descrizione ricevuta dal provider è solo metadato descrittivo: NON dimostra che l\'immagine rispetti il brief. Verifica ogni HARD gate confrontando l\'anteprima con ciò che era richiesto; Vision approva la versione solo dopo questo controllo. Il divisore fra controlli e anteprima può essere trascinato.",')
replace_one(
    path,
    '            "Descrivi ciò che è realmente visibile nell\'immagine: soggetto, scena, composizione e dettagli utili al controllo.",',
    '            "Descrizione fattuale di ciò che è realmente visibile. Non usare questa descrizione come prova di conformità al brief.",')
replace_one(path, '            Labeled("Descrizione dell\'immagine candidata", description),', '            Labeled("Descrizione del provider / della Candidate · NON è una prova di conformità", description),')
replace_one(
    path,
    '                Text = "Spunta un controllo solo dopo averlo verificato. Un controllo obbligatorio non spuntato viene trattato come FAIL e blocca l\'approvazione.",',
    '                Text = "Spunta un controllo solo dopo averlo verificato sui PIXEL reali, non sulla descrizione del provider. Chiediti anche se pagheresti per trovare questa pagina in un libro finito. Un controllo HARD non spuntato è FAIL e blocca l\'approvazione.",')

# 5) Regression gate: counted theme must become atomic and editorial readiness must stay HARD.
path = "tests/Diez.VisualBook.Pianist/Program.cs"
anchor = '''    Require(!duplicateProgress.ReadyForPublication && duplicateProgress.Problems.Any(p => p.Contains("duplicat", StringComparison.OrdinalIgnoreCase)),\n        "Due pagine diverse che usano lo stesso identico file devono bloccare la readiness del libro visuale.");\n'''
addition = '''\n    var aggregateSetup = SaveSetup(NewProject(BookTypeCatalog.ColoringBook), BookTypeCatalog.ColoringBook, 3, "3 soggetti di Halloween");\n    var aggregateProject = JsonSerializer.Deserialize<PreviewProject>(aggregateSetup.ProjectJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;\n    PromptMasterStateStore.SaveDraft(aggregateProject, 3, "3 images: 1 per ogni soggetto", "un'unica image con 3 illustrazioni ognuna", string.Empty);\n    var aggregatePrompt = VisualHardPromptContractCompiler.Build(aggregateProject, new AiExchangeWorkUnit\n    {\n        Position = 1,\n        Code = "IMG-001",\n        ContentType = AiExchangeContentTypes.Image\n    });\n    Require(aggregatePrompt.Contains("SERIES SUBJECT ASSIGNMENT — HARD", StringComparison.OrdinalIgnoreCase),\n        "Un soggetto aggregato di serie deve essere materializzato come assegnazione atomica per Work Unit.");\n    Require(!aggregatePrompt.Contains("PRIMARY SUBJECT — HARD LOCK: 3 soggetti di Halloween", StringComparison.OrdinalIgnoreCase),\n        "Il conteggio globale dei soggetti non deve più diventare il PRIMARY SUBJECT della singola immagine.");\n    Require(aggregatePrompt.Contains("item 1 of 3", StringComparison.OrdinalIgnoreCase),\n        "Il prompt atomico deve dichiarare la posizione della Work Unit nel piano soggetti.");\n    Require(!aggregatePrompt.Contains("USER REQUIREMENT — HARD: 3 images", StringComparison.OrdinalIgnoreCase),\n        "Le istruzioni sul numero di immagini appartengono all'orchestrazione del lotto, non ai pixel della singola Work Unit.");\n    Require(aggregatePrompt.Contains("Do not combine multiple requested series illustrations into one canvas", StringComparison.OrdinalIgnoreCase),\n        "Il divieto utente di accorpare le illustrazioni deve diventare un vincolo atomico non ambiguo.");\n    Require(VisionHardGatePolicy.IsHard(VisionHardGatePolicy.EditorialReadiness),\n        "La qualità editoriale/pubblicabile deve restare un HARD gate Vision.");\n'''
insert_after(path, anchor, addition)

print("Round 4 semantic coloring patch applied successfully.")
