<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DiezPublishingStudio</AssemblyName>
    <RootNamespace>DiezPublishingStudio</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.8.0-preview</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.3" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>
</Project>
